### ISSUE TITLE
Dimmers do not accept values below 30%

### ISSUE THREAD

**Issue by StefanOltmann** [pitschr/knx-link#89]
My dimmers use the DPT5.SCALING type.

I found that I can't set values below 30% to them using knx-core.
The same works with calimero-project.

I looked at this problem using the ETS5 group monitor and noticed that the DPT information seems to be missing.

Is this a bug or a misconfiguration on my site?

Please see this screenshot:
![group_monitor](https://user-images.githubusercontent.com/9299303/103478467-35b7ca00-4dc7-11eb-94bc-3f19ee8c4f9f.png)

**Comment by pitschr** [comment]
Hi Stefan.

DPT information is not a part of KNX packets. Therefore, displaying DPT is the job of ETS based on the KNXPROJ file.

Sorry, I cannot reproduce that. Setting by bytes
```
DPT5Value{dpt=DPT5{id=5.001, description=Scaling (%)}, unsignedValue=30.19607843137255, rawUnsignedValue=77, byteArray=0x4D}
DPT5Value{dpt=DPT5{id=5.001, description=Scaling (%)}, unsignedValue=20.0, rawUnsignedValue=51, byteArray=0x33}
DPT5Value{dpt=DPT5{id=5.001, description=Scaling (%)}, unsignedValue=10.196078431372548, rawUnsignedValue=26, byteArray=0x1A}
DPT5Value{dpt=DPT5{id=5.001, description=Scaling (%)}, unsignedValue=0.0, rawUnsignedValue=0, byteArray=0x00}
DPT5Value{dpt=DPT5{id=5.001, description=Scaling (%)}, unsignedValue=0.0, rawUnsignedValue=0, byteArray=0x00}
DPT5Value{dpt=DPT5{id=5.001, description=Scaling (%)}, unsignedValue=10.196078431372548, rawUnsignedValue=26, byteArray=0x1A}
DPT5Value{dpt=DPT5{id=5.001, description=Scaling (%)}, unsignedValue=20.0, rawUnsignedValue=51, byteArray=0x33}
```

Set by values (0..255)
```
DPT5Value{dpt=DPT5{id=5.001, description=Scaling (%)}, unsignedValue=0.0, rawUnsignedValue=0, byteArray=0x00}
DPT5Value{dpt=DPT5{id=5.001, description=Scaling (%)}, unsignedValue=3.9215686274509802, rawUnsignedValue=10, byteArray=0x0A}
DPT5Value{dpt=DPT5{id=5.001, description=Scaling (%)}, unsignedValue=7.8431372549019605, rawUnsignedValue=20, byteArray=0x14}
DPT5Value{dpt=DPT5{id=5.001, description=Scaling (%)}, unsignedValue=11.764705882352942, rawUnsignedValue=30, byteArray=0x1E}
DPT5Value{dpt=DPT5{id=5.001, description=Scaling (%)}, unsignedValue=15.686274509803921, rawUnsignedValue=40, byteArray=0x28}
DPT5Value{dpt=DPT5{id=5.001, description=Scaling (%)}, unsignedValue=19.607843137254903, rawUnsignedValue=50, byteArray=0x32}
DPT5Value{dpt=DPT5{id=5.001, description=Scaling (%)}, unsignedValue=23.529411764705884, rawUnsignedValue=60, byteArray=0x3C}
DPT5Value{dpt=DPT5{id=5.001, description=Scaling (%)}, unsignedValue=27.45098039215686, rawUnsignedValue=70, byteArray=0x46}
DPT5Value{dpt=DPT5{id=5.001, description=Scaling (%)}, unsignedValue=31.372549019607842, rawUnsignedValue=80, byteArray=0x50}
DPT5Value{dpt=DPT5{id=5.001, description=Scaling (%)}, unsignedValue=35.294117647058826, rawUnsignedValue=90, byteArray=0x5A}
... lines omitted...
DPT5Value{dpt=DPT5{id=5.001, description=Scaling (%)}, unsignedValue=86.27450980392157, rawUnsignedValue=220, byteArray=0xDC}
DPT5Value{dpt=DPT5{id=5.001, description=Scaling (%)}, unsignedValue=90.19607843137256, rawUnsignedValue=230, byteArray=0xE6}
DPT5Value{dpt=DPT5{id=5.001, description=Scaling (%)}, unsignedValue=94.11764705882354, rawUnsignedValue=240, byteArray=0xF0}
DPT5Value{dpt=DPT5{id=5.001, description=Scaling (%)}, unsignedValue=98.03921568627452, rawUnsignedValue=250, byteArray=0xFA}
DPT5Value{dpt=DPT5{id=5.001, description=Scaling (%)}, unsignedValue=100.0, rawUnsignedValue=255, byteArray=0xFF}
```

Given examples above, I see that DPT5.SCALING works with 0-100% range.

I tried it by myself using the `knx-demo-tty-monitor` project:
<img width="930" alt="Bildschirmfoto 2021-01-03 um 16 10 57" src="https://user-images.githubusercontent.com/25742159/103481985-81c23900-4dde-11eb-8711-06ba5eacfc1b.png">

May you let me know how you set the value using knx-core? A JUnit test case would be sufficient for me.
Just for sake of clarification, when setting value. Do you mean that it won't set below 30% but above it is possible? 

My first guess would be that you have a minimum % set in ETS for your dimmer, but as you say that it works with calimero project, then it seems be something else. But I rather not use the calimero project as reference, therefore, I suggest to use the ETS instead:

May you try capture the packets using the wireshark and try to set the value using the ETS itself. And then try to set the value using the knx-core. The APCI data should be same, at least theoretically. If not then share it with me so that I can investigate it. Thanks.

**Comment by StefanOltmann** [comment]
Hi Christoph.

It looks like that values lower than 30% have only a length of 1 as opposed to ETS5 sent values that are always of length 2.

The group address is of type "5.001" in ETS5.

Wireshark was indeed necessary here because ETS5 group monitor displayed the same hex string value (similar to the summary here), but looking into the cEMI block this difference seems to be the problem.

The KNX device is a "Theben DM 8-2 T FIX 2".

**Setting for 10% with ETS5 (working)**
![10_percent_ets](https://user-images.githubusercontent.com/9299303/103484533-caceb900-4def-11eb-8c10-fb9a3040b46f.PNG)

**Setting 10% with knx-link (not working)**
![10_percent_knxlink](https://user-images.githubusercontent.com/9299303/103484536-cdc9a980-4def-11eb-918e-60e6071cdf03.PNG)

**Setting for 0% with ETS5 (working)**
![0_percent_ets](https://user-images.githubusercontent.com/9299303/103484592-3a44a880-4df0-11eb-877b-5bc007d23651.PNG)

**Setting for 0% with knx-link (not working)**
![0_percent_knxlink](https://user-images.githubusercontent.com/9299303/103484598-42044d00-4df0-11eb-83d3-eea9510d39c0.PNG)

**Setting for 50% with ETS5 (working)**
![50_percent_ets](https://user-images.githubusercontent.com/9299303/103484639-acb58880-4df0-11eb-9c86-2a224b8c3261.PNG)

**Setting for 50% with knx-link (working)**
![50_percent_knxlink](https://user-images.githubusercontent.com/9299303/103484644-b939e100-4df0-11eb-9976-0e921bd2339e.PNG)

This is my code:
```
package de.stefan_oltmann.smarthome.server.knx

import li.pitschmann.knx.core.address.GroupAddress
import li.pitschmann.knx.core.communication.DefaultKnxClient
import li.pitschmann.knx.core.config.ConfigBuilder
import li.pitschmann.knx.core.datapoint.DPT5
import kotlin.math.roundToInt

fun main() {

    val config = ConfigBuilder
        .tunneling()
        .build()

    DefaultKnxClient.createStarted(config).use { client ->

        val percent = 10;

        val percentBase255 = (percent / 100.0 * 255).roundToInt()

        client.writeRequest(GroupAddress.of("3/1/12"), DPT5.SCALING.of(percentBase255))
    }
}
```

**Comment by pitschr** [comment]
Thanks for providing, it seems the ETS is always sending APCI in extra bytes. The issue seems be related to the implementation:
https://github.com/pitschr/knx-link/blob/master/knx-core/src/main/java/li/pitschmann/knx/core/cemi/CEMI.java#L151

I need to find out the section where it is described in the specification before I just remove that one.

**Comment by pitschr** [comment]
Question: Is the setting of percent working, meaning, is your dimming actuator accepting and applying the changes? Or is just the DPT info is not visible in the ETS monitor?

**Comment by StefanOltmann** [comment]
> Question: Is the setting of percent working, meaning, is your dimming actuator accepting and applying the changes? Or is just the DPT info is not visible in the ETS monitor?

No, the device does not accept the value send by knx-link. It's just ignored. It does not show up in my group monitor plugin that watches READ responses.

As I wanted to check if knx-link actually sends out s package I noticed the missing DPT values.

It would be helpful if ETS would flag invalid packages directly.

**Comment by pitschr** [comment]
I have found the bug, but it is bit complicated. There are two KNX packets: one standard with APCI data as separate octets. And one "optimized" version for data which contains less than 6 bits, this type of APCI data is not separated.

My initially understanding was, as long the value are below 6 bits, it is automatically considered as optimized. But seems not be the case. The optimization is based on the datapoint type (e.g. DPT1 uses optimized version while DPT5 is not using the optimized version)

This means that methods like
`li.pitschmann.knx.core.communication.KnxClient#writeRequest(li.pitschmann.knx.core.address.GroupAddress, byte[])` are useless unless I add an optimized flag which causes more confusion and will be error-prone.

But for `li.pitschmann.knx.core.communication.KnxClient#writeRequest(li.pitschmann.knx.core.address.GroupAddress, li.pitschmann.knx.core.datapoint.value.DataPointValue)` it is not a problem, because I can hardcode which DataPointValue is using the optimized version and which are not using it.

I think that it is easier to get rid off the first method `byte[]` rather than adding a flag that no one will understand it without reading the KNX specification papers explaining about the optimized section in CEMI.

I just would like to hear your voice if you see a strong reason to keep the `byte[]`?!

**Comment by StefanOltmann** [comment]
Thank you for this interesting insight. :)

> I just would like to hear your voice if you see a strong reason to keep the `byte[]`?!

No, I don't. I would not have used it because it feels to be low level API and the other API is way more convenient. I don't think that someone would really need that. At least I would like to hear that strong reason, too. ;)

**Comment by pitschr** [comment]
It was initially added in case a specific (rare) data point type has not been added to the library (yet). By removing `byte[]` it is required to implement a class that implements the public interface `DataPointValue`. As compromise I could imagine to create e.g. `RawDataPointValue` that just wraps the byte array. Not sure if it would be valuable.

Anyway, it is not a blocker, it is just not comfortable than providing the byte array only.

**Comment by StefanOltmann** [comment]
>  As compromise I could imagine to create e.g. `RawDataPointValue` that just wraps the byte array. Not sure if it would be valuable.

I see that there is value, but I would only do it if it's not too much work to be honest.

Chances are good that you don't abandon this project tommorow and would rather add support for new data point types to use them in a convenient way than using that API.

Also this is open source and if I would have such a case and you wouldn't do it I could try myself to add it.

So there is no urgent need for that I guess.

**Comment by pitschr** [comment]
I pushed the changes to https://github.com/pitschr/knx-link/tree/master-2021-01-03 branch. Can you please check if that fixes the issue for you? The optimization is now done based on the DPTxValue.

Example:
https://github.com/pitschr/knx-link/blob/master-2021-01-03/knx-core/src/main/java/li/pitschmann/knx/core/datapoint/value/DPT1Value.java

--> which implements the interface (this is a marker interface, therefore, without any methods): 
https://github.com/pitschr/knx-link/blob/master-2021-01-03/knx-core/src/main/java/li/pitschmann/knx/core/datapoint/value/PayloadOptimizable.java

It is consumed by the CEMI (line #313):
https://github.com/pitschr/knx-link/blob/master-2021-01-03/knx-core/src/main/java/li/pitschmann/knx/core/cemi/CEMI.java#L313

**Comment by pitschr** [comment]
p.s. if you think there is a better naming than "PayloadOptimizable" let me know it. Finding the proper naming is always hard :-D

**Comment by StefanOltmann** [comment]
> p.s. if you think there is a better naming than "PayloadOptimizable" let me know it. Finding the proper naming is always hard 🤣

"There are two hard things in computer science: cache invalidation, naming things, and off-by-one errors." 🤣

**Comment by StefanOltmann** [comment]
On a side note:
I just noticed IDEA doesn't compile the code of DPT14.java on Windows in the first place because of the special characters in the units for ACTIVITY (line 130) and CONDUCTANCE (line 394). I don't know why it does not read the file as UTF-8 or UNICODE but with the windows-1252 charset. Maybe an IDEA related problem. Easy to fix of course, but maybe there is a way to escape it so that also the Windows default charset is also fine with it.

**Comment by StefanOltmann** [comment]
> 
> 
> I pushed the changes to https://github.com/pitschr/knx-link/tree/master-2021-01-03 branch. Can you please check if that fixes the issue for you? 

Yes, i tested it out and it works fine.

`DPT5.SCALING` and `DPT5.PERCENT_U8` work with my dimmers on all values as they should and thanks to the other changes using them is now very straight forward.

Awesome! 👍 

```
    DefaultKnxClient.createStarted().use { client ->

        val percent = 10;

        client.writeRequest(GroupAddress.of("3/1/12"), DPT5.SCALING.of(percent))
    }
```

**Comment by pitschr** [comment]
the changes have been merged to master branch. I'll create a new release version as soon the other issues have been fixed as well.

**Comment by StefanOltmann** [comment]
Very nice!
